# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_assetrecord_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetrecord',
            old_name='asset_obj',
            new_name='server_obj',
        ),
    ]
